"""your migration description

Revision ID: 5da101e635fd
Revises: 8869774bf7cd
Create Date: 2022-01-05 11:41:21.044211

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5da101e635fd'
down_revision = '8869774bf7cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assets', sa.Column('hashed_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assets', 'hashed_at')
    # ### end Alembic commands ###
