"""your migration description

Revision ID: 8869774bf7cd
Revises: 306c4571ab00
Create Date: 2022-01-05 11:08:34.950475

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8869774bf7cd'
down_revision = '306c4571ab00'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assets', sa.Column('filename', sa.String(length=512), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assets', 'filename')
    # ### end Alembic commands ###
