"""your migration description

Revision ID: b91257b99d65
Revises: b21d33852dd2
Create Date: 2022-01-04 22:49:24.607898

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b91257b99d65'
down_revision = 'b21d33852dd2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('collections', sa.Column('created_at', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('collections', 'created_at')
    # ### end Alembic commands ###
